spring:
  autoconfigure:
    exclude: org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1
